# these have been copied into helm-kind/templates directory
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: jenkins-jcasc
        imagePullPolicy: Never
        image: jenkins:jan2021
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: 750m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 50Mi