version: '3.3'

services:

  jenkins:
    container_name: jenkins_container_${TAG}
    image: jenkins:${TAG}
    build:
      context: .
      dockerfile: ./build.Dockerfile
    ports:
      - '8080:8080'
      - '50000:50000'
    networks:
      - default
    volumes:
      - /Users/jeff/Desktop/Jenkins_Home:/var/jenkins_home
      - /Users/jeff/Desktop/projects/cloud/kind/jenkins-kind/docker_images/dev/jenkins.yml:/usr/share/jenkins/ref/jenkins.yml
      - /var/run/docker.sock:/var/run/docker.sock
      # map local development into jenkins.yml in container for quick testing


networks:
  default:
