# these have been copied into helm-kind/templates directory
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: jenkins-jcasc
        imagePullPolicy: Never
        image: jenkins:prod
        ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 50000
            protocol: TCP
        # resources:
        #   limits:
        #     cpu: 750m 
        #     memory: 512Mi
        #   requests:
        #     cpu: 300m
        #     memory: 50Mi
        volumeMounts:
          - mountPath: /var
            name: jenkins
            subPath: jenkins_home
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins-claim